[book]
authors = ["pintergreg"]
multilingual = false
src = "src"
title = "Jegyzet"
description = "Szoftverfejlesztés multinacionális vállalatoknál"

[output.html]
mathjax-support = true
additional-js = ["context-cards.js", "mermaid.min.js", "jsmind.js"]
additional-css = ["jsmind.css"]

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]
