name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
        cargo install-update -a
    - name: Build
      run: cd $GITHUB_WORKSPACE && mdbook build
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: $GITHUB_WORKSPACE/book # The folder the action should deploy.
      
            
