name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        cargo install-update -a
    - name: Build
      run: cd $GITHUB_WORKSPACE && mdbook build
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: book # The folder the action should deploy.
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: $HOME/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: $HOME/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
 
